-- Table: public.doors

-- DROP TABLE IF EXISTS public.doors;

CREATE TABLE IF NOT EXISTS public.common
(
    id integer NOT NULL DEFAULT nextval('common_id_seq1'::regclass),
    user_id integer,
    jamb_width_unit_cost_psf numeric(12,2),
    jamb_depth_unit_cost_psf numeric(12,2),
    stile_width_thickness_unit_cost_psf numeric(12,2),
    over_10_door_unit_cost_psf numeric(12,2),
    over_14_unit_unit_cost_psf numeric(12,2),
    door_swing_from_ext_unit_cost_psf numeric(12,2),
    hardware_prep_type_unit_cost_psf numeric(12,2),
    threshold_type_unit_cost_psf numeric(12,2),
    bugscreens_unit_cost_psf numeric(12,2),
    remodel_unit_cost_psf numeric(12,2),
    out_of_town_install_unit_cost_psf numeric(12,2),
    freight_in_unit_cost_psf numeric(12,2),
    other_charge_2_unit_cost_psf numeric(12,2),
    unit_size_types_width_inches numeric(12,2),
    unit_size_types_height_inches numeric(12,2),
    unit_size_types_sqft_lft numeric(12,2),
    unit_size_types_unit_cost_psf numeric(12,2),
    unit_size_types_estimated_cost numeric(12,2),
    unit_size_types_price numeric(12,2),
    unit_functions_width_inches numeric(12,2),
    unit_functions_height_inches numeric(12,2),
    unit_functions_sqft_lft numeric(12,2),
    unit_functions_unit_cost_psf numeric(12,2),
    unit_functions_estimated_cost numeric(12,2),
    unit_functions_price numeric(12,2),
    arch_unit_types_width_inches numeric(12,2),
    arch_unit_types_height_inches numeric(12,2),
    arch_unit_types_sqft_lft numeric(12,2),
    arch_unit_types_unit_cost_psf numeric(12,2),
    arch_unit_estimated_cost numeric(12,2),
    arch_unit_price numeric(12,2),
    arch_door_types_width_inches numeric(12,2),
    arch_door_types_height_inches numeric(12,2),
    arch_door_types_sqft_lft numeric(12,2),
    arch_door_types_unit_cost_psf numeric(12,2),
    arch_door_estimated_cost numeric(12,2),
    arch_door_price numeric(12,2),
    roller_latches_prep_width_inches numeric(12,2),
    roller_latches_prep_height_inches numeric(12,2),
    roller_latches_prep_sqft_lft numeric(12,2),
    roller_latches_prep_unit_cost_psf numeric(12,2),
    roller_latches_prep_estimated_cost numeric(12,2),
    roller_latches_prep_price numeric(12,2),
    pull_handles_width_inches numeric(12,2),
    pull_handles_height_inches numeric(12,2),
    pull_handles_sqft_lft numeric(12,2),
    pull_handles_unit_cost_psf numeric(12,2),
    pull_handles_estimated_cost numeric(12,2),
    pull_handles_price numeric(12,2),
    deadbolt_installation_types_width_inches numeric(12,2),
    deadbolt_installation_types_height_inches numeric(12,2),
    deadbolt_installation_types_sqft_lft numeric(12,2),
    deadbolt_installation_types_unit_cost_psf numeric(12,2),
    deadbolt_installation_estimated_cost numeric(12,2),
    deadbolt_installation_price numeric(12,2),
    threshold_ht_width_inches numeric(12,2),
    threshold_ht_height_inches numeric(12,2),
    threshold_ht_sqft_lft numeric(12,2),
    threshold_ht_unit_cost_psf numeric(12,2),
    threshold_ht_estimated_cost numeric(12,2),
    threshold_ht_price numeric(12,2),
    trim_exterior_width_inches numeric(12,2),
    trim_exterior_height_inches numeric(12,2),
    trim_exterior_sqft_lft numeric(12,2),
    trim_exterior_unit_cost_psf numeric(12,2),
    trim_exterior_estimated_cost numeric(12,2),
    trim_exterior_price numeric(12,2),
    trim_interior_width_inches numeric(12,2),
    trim_interior_height_inches numeric(12,2),
    trim_interior_sqft_lft numeric(12,2),
    trim_interior_unit_cost_psf numeric(12,2),
    trim_interior_estimated_cost numeric(12,2),
    trim_interior_price numeric(12,2),
    glass_temp_ig_width_inches numeric(12,2),
    glass_temp_ig_height_inches numeric(12,2),
    glass_temp_ig_sqft_lft numeric(12,2),
    glass_temp_ig_unit_cost_psf numeric(12,2),
    glass_temp_ig_estimated_cost numeric(12,2),
    glass_temp_ig_price numeric(12,2),
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    total_estimated_cost numeric,
    total_price numeric,
    over_10_door_estimated_cost numeric(12,2),
    over_10_door_price numeric(12,2),
    over_14_unit_estimated_cost numeric(12,2),
    over_14_unit_price numeric(12,2),
    bugscreens_estimated_cost numeric(12,2),
    bugscreens_price numeric(12,2),
    remodel_estimated_cost numeric(12,2),
    remodel_price numeric(12,2),
    customer_id integer,
    img_url text[] COLLATE pg_catalog."default",
    CONSTRAINT common_pkey1 PRIMARY KEY (id)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.common
    OWNER to postgres;